# Generated by Django 5.2 on 2025-06-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_duration',
            field=models.IntegerField(blank=True, help_text='Interview duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='transcript',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
