# Generated by Django 5.2 on 2025-04-22 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommender', '0002_job_is_active_job_posting_date_job_salary_range_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posting_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
    ]
