# Generated by Django 5.2 on 2025-05-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommender', '0003_remove_job_is_active_remove_job_posting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
