# Generated by Django 5.2 on 2025-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommender', '0006_student_email_student_linkedin_profile_student_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('alumni', 'Alumni Model'), ('job', 'Job Model')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ML Model Info',
                'verbose_name_plural': 'ML Model Info',
            },
        ),
    ]
